#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PI_HOST="${PI_HOST:-${1:-monad-rpi5.local}}"
SMOKE_PROFILE="${SMOKE_PROFILE:-wireless_spec}"

# One-device real defaults.
RUN_PI="${RUN_PI:-true}"
RUN_PI_PASSIVE="${RUN_PI_PASSIVE:-false}"
INJECT_HYPOTHETICAL_METRICS="${INJECT_HYPOTHETICAL_METRICS:-false}"
REAL_DATA_ENFORCE="${REAL_DATA_ENFORCE:-true}"
REQUIRE_REAL_WIFI="${REQUIRE_REAL_WIFI:-true}"
REQUIRE_REAL_BLE="${REQUIRE_REAL_BLE:-true}"
REQUIRE_REAL_CSI="${REQUIRE_REAL_CSI:-true}"
REQUIRE_CSI_FRAMES_MIN="${REQUIRE_CSI_FRAMES_MIN:-1}"
DO_BUILD="${DO_BUILD:-false}"
RESET_STATE="${RESET_STATE:-false}"
RESET_METRICS="${RESET_METRICS:-false}"
RESET_GRAFANA="${RESET_GRAFANA:-false}"
CLEANUP="${CLEANUP:-false}"

WIRELESS_SPEC_DURATION_S="${WIRELESS_SPEC_DURATION_S:-30}"
WIRELESS_SPEC_INTERVAL_S_PI="${WIRELESS_SPEC_INTERVAL_S_PI:-3}"
WIRELESS_SPEC_BLE_TIMEOUT_S="${WIRELESS_SPEC_BLE_TIMEOUT_S:-12}"
WIRELESS_SPEC_CSI_TIMEOUT_S="${WIRELESS_SPEC_CSI_TIMEOUT_S:-15}"
WIRELESS_SPEC_ARTIFACT_STRIDE="${WIRELESS_SPEC_ARTIFACT_STRIDE:-0}"

cd "${ROOT_DIR}"

RUN_PI="${RUN_PI}" \
RUN_PI_PASSIVE="${RUN_PI_PASSIVE}" \
PI_HOST="${PI_HOST}" \
SMOKE_PROFILE="${SMOKE_PROFILE}" \
INJECT_HYPOTHETICAL_METRICS="${INJECT_HYPOTHETICAL_METRICS}" \
REAL_DATA_ENFORCE="${REAL_DATA_ENFORCE}" \
REQUIRE_REAL_WIFI="${REQUIRE_REAL_WIFI}" \
REQUIRE_REAL_BLE="${REQUIRE_REAL_BLE}" \
REQUIRE_REAL_CSI="${REQUIRE_REAL_CSI}" \
REQUIRE_CSI_FRAMES_MIN="${REQUIRE_CSI_FRAMES_MIN}" \
DO_BUILD="${DO_BUILD}" \
RESET_STATE="${RESET_STATE}" \
RESET_METRICS="${RESET_METRICS}" \
RESET_GRAFANA="${RESET_GRAFANA}" \
CLEANUP="${CLEANUP}" \
WIRELESS_SPEC_DURATION_S="${WIRELESS_SPEC_DURATION_S}" \
WIRELESS_SPEC_INTERVAL_S_PI="${WIRELESS_SPEC_INTERVAL_S_PI}" \
WIRELESS_SPEC_BLE_TIMEOUT_S="${WIRELESS_SPEC_BLE_TIMEOUT_S}" \
WIRELESS_SPEC_CSI_TIMEOUT_S="${WIRELESS_SPEC_CSI_TIMEOUT_S}" \
WIRELESS_SPEC_ARTIFACT_STRIDE="${WIRELESS_SPEC_ARTIFACT_STRIDE}" \
"${ROOT_DIR}/scripts/smoke/v3_end_to_end_smoke.sh"
