#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

CONTROL_PLANE_IFACE="${CONTROL_PLANE_IFACE:-wlan0}"
WIFI_SCAN_IFACE="${WIFI_SCAN_IFACE:-${CONTROL_PLANE_IFACE}}"
CSI_MEASURE_IFACE="${CSI_MEASURE_IFACE:-}"

echo "Running dual-band stable profile (control=2.4GHz, csi=5GHz)..."
echo "CONTROL_PLANE_IFACE=${CONTROL_PLANE_IFACE}"
echo "WIFI_SCAN_IFACE=${WIFI_SCAN_IFACE}"
if [[ -n "${CSI_MEASURE_IFACE}" ]]; then
  echo "CSI_MEASURE_IFACE=${CSI_MEASURE_IFACE}"
else
  echo "CSI_MEASURE_IFACE=auto"
fi

CONTROL_PLANE_IFACE="${CONTROL_PLANE_IFACE}" \
WIFI_SCAN_IFACE="${WIFI_SCAN_IFACE}" \
CONTROL_PLANE_BAND_EXPECT="${CONTROL_PLANE_BAND_EXPECT:-2.4}" \
CSI_MEASURE_IFACE="${CSI_MEASURE_IFACE}" \
CSI_MEASURE_BAND_EXPECT="${CSI_MEASURE_BAND_EXPECT:-5}" \
CSI_REQUIRE_SEPARATE_IFACE="${CSI_REQUIRE_SEPARATE_IFACE:-true}" \
CSI_IFACE_FLAG="${CSI_IFACE_FLAG:-auto}" \
AUTO_SWITCH_CONTROL_PLANE_IFACE="${AUTO_SWITCH_CONTROL_PLANE_IFACE:-true}" \
AUTO_SWITCH_CSI_MEASURE_IFACE="${AUTO_SWITCH_CSI_MEASURE_IFACE:-true}" \
SINGLE_RADIO_MODE="${SINGLE_RADIO_MODE:-false}" \
REQUIRE_WIFI_CONTROL="${REQUIRE_WIFI_CONTROL:-true}" \
ALLOW_WIFI_DISRUPTIVE_CSI="${ALLOW_WIFI_DISRUPTIVE_CSI:-false}" \
SEPARATE_MEASURE_AND_REPORT="${SEPARATE_MEASURE_AND_REPORT:-true}" \
RESTART_CONTROL_PLANE_BEFORE_REPORT="${RESTART_CONTROL_PLANE_BEFORE_REPORT:-false}" \
ALLOW_WIFI_CONTROL_PLANE_RESTART="${ALLOW_WIFI_CONTROL_PLANE_RESTART:-false}" \
CSI_DEFAULT_FEIT_FREQ_MHZ="${CSI_DEFAULT_FEIT_FREQ_MHZ:-5240}" \
CSI_DEFAULT_FEIT_CHANNEL_WIDTH_MHZ="${CSI_DEFAULT_FEIT_CHANNEL_WIDTH_MHZ:-20}" \
REQUIRE_REAL_CSI="${REQUIRE_REAL_CSI:-true}" \
CSI_REQUIRE_EVIDENCE="${CSI_REQUIRE_EVIDENCE:-true}" \
CSI_MIN_OUTPUT_FILES="${CSI_MIN_OUTPUT_FILES:-1}" \
bash scripts/smoke/pi_wifi_csi_stable.sh
