#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PI_HOST="${PI_HOST:-${1:-monad-rpi5.local}}"
CONTROL_PLANE_IFACE="${CONTROL_PLANE_IFACE:-wlan0}"
WIFI_SCAN_IFACE="${WIFI_SCAN_IFACE:-${CONTROL_PLANE_IFACE}}"
BLE_SCAN_IFACE="${BLE_SCAN_IFACE:-hci0}"
CSI_MEASURE_IFACE="${CSI_MEASURE_IFACE:-${CONTROL_PLANE_IFACE}}"

EXPERIMENT_JSON_FILE="${EXPERIMENT_JSON_FILE:-${ROOT_DIR}/docs/examples/experiment_execution_window_design.json}"
SMOKE_PROFILE="${SMOKE_PROFILE:-design-json}"
SMOKE_TITLE_PREFIX="${SMOKE_TITLE_PREFIX:-Fleet Design JSON}"
SMOKE_TAGS_CSV="${SMOKE_TAGS_CSV:-fleet,smoke:v3,design-json,created-by:monad-fleet}"
EXPERIMENT_TIME_SHIFT_START_MINUTES="${EXPERIMENT_TIME_SHIFT_START_MINUTES:--2}"

RUN_PI="${RUN_PI:-true}"
RUN_PI_PASSIVE="${RUN_PI_PASSIVE:-false}"
REAL_DATA_ENFORCE="${REAL_DATA_ENFORCE:-true}"
REQUIRE_REAL_WIFI="${REQUIRE_REAL_WIFI:-true}"
REQUIRE_REAL_BLE="${REQUIRE_REAL_BLE:-true}"
REQUIRE_REAL_CSI="${REQUIRE_REAL_CSI:-false}"
REQUIRE_CSI_FRAMES_MIN="${REQUIRE_CSI_FRAMES_MIN:-0}"
INJECT_HYPOTHETICAL_METRICS="${INJECT_HYPOTHETICAL_METRICS:-false}"

DO_BUILD="${DO_BUILD:-true}"
RESET_STATE="${RESET_STATE:-false}"
RESET_METRICS="${RESET_METRICS:-false}"
RESET_GRAFANA="${RESET_GRAFANA:-false}"
CLEANUP="${CLEANUP:-false}"

SINGLE_RADIO_MODE="${SINGLE_RADIO_MODE:-true}"
SINGLE_RADIO_WIFI_PROFILE="${SINGLE_RADIO_WIFI_PROFILE:-auto}"
ALLOW_WIFI_DISRUPTIVE_CSI="${ALLOW_WIFI_DISRUPTIVE_CSI:-true}"
SEPARATE_MEASURE_AND_REPORT="${SEPARATE_MEASURE_AND_REPORT:-true}"
RESTART_CONTROL_PLANE_BEFORE_REPORT="${RESTART_CONTROL_PLANE_BEFORE_REPORT:-true}"
CONTROL_PLANE_RESTART_IFACE="${CONTROL_PLANE_RESTART_IFACE:-${CONTROL_PLANE_IFACE}}"
ALLOW_WIFI_CONTROL_PLANE_RESTART="${ALLOW_WIFI_CONTROL_PLANE_RESTART:-false}"

CSI_REQUIRE_EVIDENCE="${CSI_REQUIRE_EVIDENCE:-false}"
CSI_MIN_OUTPUT_FILES="${CSI_MIN_OUTPUT_FILES:-0}"
CSI_TRAFFIC_IFACE="${CSI_TRAFFIC_IFACE:-${CONTROL_PLANE_IFACE}}"
AGENT_RUN_TIMEOUT_S="${AGENT_RUN_TIMEOUT_S:-1200}"
ARTIFACT_UPLOAD_DURING_MEASURE="${ARTIFACT_UPLOAD_DURING_MEASURE:-false}"

cd "${ROOT_DIR}"

RUN_PI="${RUN_PI}" \
RUN_PI_PASSIVE="${RUN_PI_PASSIVE}" \
PI_HOST="${PI_HOST}" \
SMOKE_PROFILE="${SMOKE_PROFILE}" \
SMOKE_TITLE_PREFIX="${SMOKE_TITLE_PREFIX}" \
SMOKE_TAGS_CSV="${SMOKE_TAGS_CSV}" \
EXPERIMENT_JSON_FILE="${EXPERIMENT_JSON_FILE}" \
EXPERIMENT_TIME_SHIFT_START_MINUTES="${EXPERIMENT_TIME_SHIFT_START_MINUTES}" \
CONTROL_PLANE_IFACE="${CONTROL_PLANE_IFACE}" \
WIFI_SCAN_IFACE="${WIFI_SCAN_IFACE}" \
BLE_SCAN_IFACE="${BLE_SCAN_IFACE}" \
CSI_MEASURE_IFACE="${CSI_MEASURE_IFACE}" \
REAL_DATA_ENFORCE="${REAL_DATA_ENFORCE}" \
REQUIRE_REAL_WIFI="${REQUIRE_REAL_WIFI}" \
REQUIRE_REAL_BLE="${REQUIRE_REAL_BLE}" \
REQUIRE_REAL_CSI="${REQUIRE_REAL_CSI}" \
REQUIRE_CSI_FRAMES_MIN="${REQUIRE_CSI_FRAMES_MIN}" \
INJECT_HYPOTHETICAL_METRICS="${INJECT_HYPOTHETICAL_METRICS}" \
DO_BUILD="${DO_BUILD}" \
RESET_STATE="${RESET_STATE}" \
RESET_METRICS="${RESET_METRICS}" \
RESET_GRAFANA="${RESET_GRAFANA}" \
CLEANUP="${CLEANUP}" \
SINGLE_RADIO_MODE="${SINGLE_RADIO_MODE}" \
SINGLE_RADIO_WIFI_PROFILE="${SINGLE_RADIO_WIFI_PROFILE}" \
ALLOW_WIFI_DISRUPTIVE_CSI="${ALLOW_WIFI_DISRUPTIVE_CSI}" \
SEPARATE_MEASURE_AND_REPORT="${SEPARATE_MEASURE_AND_REPORT}" \
RESTART_CONTROL_PLANE_BEFORE_REPORT="${RESTART_CONTROL_PLANE_BEFORE_REPORT}" \
CONTROL_PLANE_RESTART_IFACE="${CONTROL_PLANE_RESTART_IFACE}" \
ALLOW_WIFI_CONTROL_PLANE_RESTART="${ALLOW_WIFI_CONTROL_PLANE_RESTART}" \
CSI_REQUIRE_EVIDENCE="${CSI_REQUIRE_EVIDENCE}" \
CSI_MIN_OUTPUT_FILES="${CSI_MIN_OUTPUT_FILES}" \
CSI_TRAFFIC_IFACE="${CSI_TRAFFIC_IFACE}" \
AGENT_RUN_TIMEOUT_S="${AGENT_RUN_TIMEOUT_S}" \
ARTIFACT_UPLOAD_DURING_MEASURE="${ARTIFACT_UPLOAD_DURING_MEASURE}" \
"${ROOT_DIR}/scripts/smoke/v3_end_to_end_smoke.sh"
