#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

PI_USER="${PI_USER:-admin}"
PI_HOST="${PI_HOST:-192.168.0.211}"
PI_RECOVERY_HOSTS_CSV="${PI_RECOVERY_HOSTS_CSV:-${PI_HOST}}"
FLEET_MANAGER_HOST="${FLEET_MANAGER_HOST:-192.168.0.70}"
FLEET_MANAGER_PORT="${FLEET_MANAGER_PORT:-50060}"

CYCLES="${CYCLES:-2}"
PASSIVE_AGENT_WAIT_S="${PASSIVE_AGENT_WAIT_S:-240}"
PASSIVE_VERIFY_MAX_WAIT_S="${PASSIVE_VERIFY_MAX_WAIT_S:-900}"
PASSIVE_VERIFY_POLL_S="${PASSIVE_VERIFY_POLL_S:-15}"
CSI_COLLECTOR_CMD="${CSI_COLLECTOR_CMD:-}"
CSI_OUTPUT_PATH="${CSI_OUTPUT_PATH:-/tmp/csi.dat}"
CSI_OUTPUT_GLOB="${CSI_OUTPUT_GLOB:-}"
CSI_FRAMES_REGEX="${CSI_FRAMES_REGEX:-}"
CSI_TRAFFIC_ENABLE="${CSI_TRAFFIC_ENABLE:-true}"
CSI_TRAFFIC_TARGET="${CSI_TRAFFIC_TARGET:-}"
CSI_TRAFFIC_IFACE="${CSI_TRAFFIC_IFACE:-wlan0}"
CSI_TRAFFIC_INTERVAL_MS="${CSI_TRAFFIC_INTERVAL_MS:-100}"

SSH_CONNECT_TIMEOUT_S="${SSH_CONNECT_TIMEOUT_S:-8}"
SSH_ARGS=(
  -o "ConnectTimeout=${SSH_CONNECT_TIMEOUT_S}"
  -o BatchMode=yes
  -o StrictHostKeyChecking=accept-new
)

echo "Passive two-cycle smoke start"
echo "PI=${PI_USER}@${PI_HOST}"
echo "PI recovery hosts=${PI_RECOVERY_HOSTS_CSV}"
echo "Fleet=${FLEET_MANAGER_HOST}:${FLEET_MANAGER_PORT}"
echo "Cycles=${CYCLES}"

if ! ssh "${SSH_ARGS[@]}" "${PI_USER}@${PI_HOST}" "echo SSH_OK >/dev/null"; then
  echo "ERROR: Pi is not reachable via SSH (${PI_HOST})."
  exit 2
fi

AGENT_ID="${AGENT_ID:-}"
if [[ -z "${AGENT_ID}" ]]; then
  AGENT_ID="$(ssh "${SSH_ARGS[@]}" "${PI_USER}@${PI_HOST}" "cat /sys/class/net/wlan0/address 2>/dev/null || true" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')"
fi
if [[ -z "${AGENT_ID}" ]]; then
  echo "ERROR: Could not resolve AGENT_ID from wlan0 MAC."
  exit 3
fi
echo "Using AGENT_ID=${AGENT_ID}"

mkdir -p output/smoke_seq

for n in $(seq 1 "${CYCLES}"); do
  logfile="output/smoke_seq/$(date -u +%Y%m%dT%H%M%SZ)-passive-cycle${n}.log"
  echo "===== PASSIVE CYCLE ${n}/${CYCLES} START $(date -u +%FT%TZ) ====="
  set +e
  RUN_PI=true \
  RUN_PI_PASSIVE=true \
  PI_HOSTS_CSV="${PI_HOST}" \
  PI_RECOVERY_HOSTS_CSV="${PI_RECOVERY_HOSTS_CSV}" \
  TARGET_DEVICE_IDS_CSV="${AGENT_ID}" \
  DEVICE_PI="${AGENT_ID}" \
  FLEET_MANAGER_HOST="${FLEET_MANAGER_HOST}" \
  FLEET_MANAGER_PORT="${FLEET_MANAGER_PORT}" \
  DO_BUILD="${DO_BUILD:-false}" \
  SKIP_CORE_SERVICES_RESTART="${SKIP_CORE_SERVICES_RESTART:-true}" \
  RESET_STATE="${RESET_STATE:-false}" \
  RESET_METRICS="${RESET_METRICS:-false}" \
  CLEANUP="${CLEANUP:-false}" \
  INJECT_HYPOTHETICAL_METRICS="${INJECT_HYPOTHETICAL_METRICS:-false}" \
  REAL_DATA_ENFORCE="${REAL_DATA_ENFORCE:-true}" \
  REQUIRE_REAL_WIFI="${REQUIRE_REAL_WIFI:-true}" \
  REQUIRE_REAL_BLE="${REQUIRE_REAL_BLE:-false}" \
  REQUIRE_REAL_CSI="${REQUIRE_REAL_CSI:-true}" \
  REQUIRE_CSI_FRAMES_MIN="${REQUIRE_CSI_FRAMES_MIN:-1}" \
  SMOKE_PROFILE="${SMOKE_PROFILE:-full}" \
  FULL_DURATION_S="${FULL_DURATION_S:-30}" \
  FULL_INTERVAL_S_PI="${FULL_INTERVAL_S_PI:-5}" \
  FULL_BLE_TIMEOUT_S="${FULL_BLE_TIMEOUT_S:-15}" \
  FULL_CSI_TIMEOUT_S="${FULL_CSI_TIMEOUT_S:-45}" \
  SINGLE_RADIO_MODE="${SINGLE_RADIO_MODE:-true}" \
  SINGLE_RADIO_WIFI_PROFILE="${SINGLE_RADIO_WIFI_PROFILE:-auto}" \
  SINGLE_RADIO_RECOVERY_RETRIES="${SINGLE_RADIO_RECOVERY_RETRIES:-2}" \
  SINGLE_RADIO_RECOVERY_ROUTE_WAIT_S="${SINGLE_RADIO_RECOVERY_ROUTE_WAIT_S:-25}" \
  SINGLE_RADIO_REBOOT_ON_RECOVERY_FAIL="${SINGLE_RADIO_REBOOT_ON_RECOVERY_FAIL:-true}" \
  SEPARATE_MEASURE_AND_REPORT="${SEPARATE_MEASURE_AND_REPORT:-true}" \
  RESTART_CONTROL_PLANE_BEFORE_REPORT="${RESTART_CONTROL_PLANE_BEFORE_REPORT:-true}" \
  CONTROL_PLANE_RESTART_IFACE="${CONTROL_PLANE_RESTART_IFACE:-wlan0}" \
  CONTROL_PLANE_RESTART_DOWN_S="${CONTROL_PLANE_RESTART_DOWN_S:-2}" \
  CONTROL_PLANE_RESTART_WAIT_S="${CONTROL_PLANE_RESTART_WAIT_S:-45}" \
  PASSIVE_AGENT_WAIT_S="${PASSIVE_AGENT_WAIT_S}" \
  PASSIVE_VERIFY_MAX_WAIT_S="${PASSIVE_VERIFY_MAX_WAIT_S}" \
  PASSIVE_VERIFY_POLL_S="${PASSIVE_VERIFY_POLL_S}" \
  CSI_REQUIRE_EVIDENCE="${CSI_REQUIRE_EVIDENCE:-true}" \
  CSI_MIN_OUTPUT_FILES="${CSI_MIN_OUTPUT_FILES:-1}" \
  CSI_HARD_TIMEOUT_S="${CSI_HARD_TIMEOUT_S:-45}" \
  CSI_CLEANUP_BEFORE_CAPTURE="${CSI_CLEANUP_BEFORE_CAPTURE:-true}" \
  CSI_CLEANUP_AFTER_CAPTURE="${CSI_CLEANUP_AFTER_CAPTURE:-true}" \
  CSI_KILL_PATTERNS="${CSI_KILL_PATTERNS:-feitcsi}" \
  CSI_DEFAULT_FEIT_CHANNEL_WIDTH_MHZ="${CSI_DEFAULT_FEIT_CHANNEL_WIDTH_MHZ:-40}" \
  CSI_COLLECTOR_CMD="${CSI_COLLECTOR_CMD}" \
  CSI_OUTPUT_PATH="${CSI_OUTPUT_PATH}" \
  CSI_OUTPUT_GLOB="${CSI_OUTPUT_GLOB}" \
  CSI_FRAMES_REGEX="${CSI_FRAMES_REGEX}" \
  CSI_TRAFFIC_ENABLE="${CSI_TRAFFIC_ENABLE}" \
  CSI_TRAFFIC_TARGET="${CSI_TRAFFIC_TARGET}" \
  CSI_TRAFFIC_IFACE="${CSI_TRAFFIC_IFACE}" \
  CSI_TRAFFIC_INTERVAL_MS="${CSI_TRAFFIC_INTERVAL_MS}" \
  scripts/smoke/v3_end_to_end_smoke.sh | tee "${logfile}"
  rc=$?
  set -e
  if [[ "${rc}" != "0" ]]; then
    echo "PASSIVE cycle ${n}/${CYCLES} failed (rc=${rc}), logfile=${logfile}"
    exit "${rc}"
  fi
  echo "===== PASSIVE CYCLE ${n}/${CYCLES} END $(date -u +%FT%TZ) logfile=${logfile} ====="
done

echo "PASSIVE_TWO_CYCLE_DONE"
