#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env.aws}"
WORK_DIR="${WORK_DIR:-/tmp/fleetmanager-elabimg-build}"
ELABIMG_REPO="${ELABIMG_REPO:-https://github.com/elabftw/elabimg.git}"
ELABFTW_OWNER="${ELABFTW_OWNER:-hokanuSK}"
ELABFTW_REPO="${ELABFTW_REPO:-elabftw}"
ELABFTW_VERSION="${ELABFTW_VERSION:-scheduler-json-editor-fix}"
ELAB_WEB_IMAGE="${ELAB_WEB_IMAGE:-elabftw/elabimg:custom}"

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not found in PATH" >&2
  exit 1
fi

rm -rf "$WORK_DIR"
if command -v git >/dev/null 2>&1; then
  git clone --depth 1 "$ELABIMG_REPO" "$WORK_DIR"
else
  if ! command -v curl >/dev/null 2>&1 || ! command -v tar >/dev/null 2>&1; then
    echo "git not found, and curl+tar fallback is unavailable" >&2
    exit 1
  fi
  tmp_archive="$(mktemp -t elabimg.XXXXXX.tar.gz)"
  trap 'rm -f "$tmp_archive"' EXIT
  case "$ELABIMG_REPO" in
    https://github.com/*.git)
      archive_url="${ELABIMG_REPO%.git}/archive/refs/heads/master.tar.gz"
      ;;
    https://github.com/*)
      archive_url="${ELABIMG_REPO%/}/archive/refs/heads/master.tar.gz"
      ;;
    *)
      echo "git not found and ELABIMG_REPO is not a supported GitHub URL: $ELABIMG_REPO" >&2
      exit 1
      ;;
  esac
  mkdir -p "$WORK_DIR"
  curl -fsSL "$archive_url" -o "$tmp_archive"
  tar -xzf "$tmp_archive" -C "$WORK_DIR" --strip-components=1
fi

dockerfile="$WORK_DIR/Dockerfile"
sed -i.bak \
  "s|https://github.com/elabftw/elabftw/tarball/\$ELABFTW_VERSION|https://github.com/${ELABFTW_OWNER}/${ELABFTW_REPO}/tarball/\$ELABFTW_VERSION|g" \
  "$dockerfile"
sed -i.bak "s|mv elabftw-\\* src|mv *elabftw* src|g" "$dockerfile"
# scheduler-json-editor-fix branch has no var/ dir — make that mv optional
sed -i.bak "s|mv src/var /elabftw|mv src/var /elabftw 2>/dev/null \|\| true|g" "$dockerfile"
# Inject NODE_OPTIONS before the yarn build step to prevent OOM during asset compilation
sed -i.bak "s|ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0|ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0\nENV NODE_OPTIONS=--max-old-space-size=6144|g" "$dockerfile"
rm -f "$dockerfile.bak"

cat > "$WORK_DIR/patch_scheduler_datetime.php" << 'PHP'
<?php

declare(strict_types=1);

$file = '/elabftw/src/Models/Scheduler.php';
$src = file_get_contents($file);
if ($src === false) {
    fwrite(STDERR, "Could not read $file\n");
    exit(1);
}

$src = str_replace(
    array(
        "'2012-31-12T00:00:00+00:00'",
        "'2037-31-12T00:00:00+00:00'",
    ),
    array(
        "'2012-12-31 00:00:00'",
        "'2037-12-31 00:00:00'",
    ),
    $src
);

$old = <<<'PHP_SOURCE'
    private function normalizeDate(string $date, bool $rmDay = false): string
    {
        if (DateTime::createFromFormat(DateTime::ATOM, $date) === false) {
            $dateOnly = DateTime::createFromFormat('Y-m-d', $date);
            if ($dateOnly === false) {
                throw new ImproperActionException('Could not understand date format!');
            }
            $dateOnly->setTime(0, 1);
            // we don't want the end date to go over one day
            if ($rmDay) {
                $dateOnly->modify('-3min');
            }
            return $dateOnly->format(DateTime::ATOM);
        }
        return $date;
    }
PHP_SOURCE;

$new = <<<'PHP_SOURCE'
    private function normalizeDate(string $date, bool $rmDay = false): string
    {
        $dt = DateTime::createFromFormat(DateTime::ATOM, $date);
        if ($dt === false) {
            $dt = DateTime::createFromFormat('Y-m-d H:i:s', $date);
        }
        if ($dt === false) {
            $dt = DateTime::createFromFormat('Y-m-d', $date);
            if ($dt === false) {
                throw new ImproperActionException('Could not understand date format!');
            }
            $dt->setTime(0, 1);
            if ($rmDay) {
                $dt->modify('-3min');
            }
        }
        return $dt->format('Y-m-d H:i:s');
    }
PHP_SOURCE;

if (str_contains($src, $old)) {
    $src = str_replace($old, $new, $src);
    echo "Patched Scheduler::normalizeDate\n";
} else {
    echo "Scheduler::normalizeDate already patched or pattern changed\n";
}

if (file_put_contents($file, $src) === false) {
    fwrite(STDERR, "Could not write $file\n");
    exit(1);
}
PHP

# The hypernext branch uses BuildInfo::ID (generated by src/tools/mkbuildinfo.php via
# composer dump-autoload). The upstream elabimg Dockerfile doesn't run composer post-install
# scripts, so BuildInfo.php is never created — we append the generation step here.
cat >> "$dockerfile" << 'DOCKERFILE_APPEND'
# Generate BuildInfo.php used by TwigTrait for asset cache-busting (hypernext branch requirement)
RUN ELABFTW_VERSION="$ELABFTW_VERSION" php -d open_basedir='' /elabftw/src/tools/mkbuildinfo.php \
  && php -d open_basedir='' /usr/local/bin/composer dump-autoload -o --working-dir=/elabftw 2>&1 | tail -1 \
  && test -f /elabftw/src/Elabftw/BuildInfo.php
# Patch schema version: scheduler-json-editor-fix branch has REQUIRED_SCHEMA=187 but DB is at 208
RUN sed -i 's/REQUIRED_SCHEMA = 187/REQUIRED_SCHEMA = 208/' /elabftw/src/Elabftw/Update.php
COPY patch_scheduler_datetime.php /tmp/patch_scheduler_datetime.php
RUN php -d open_basedir='' /tmp/patch_scheduler_datetime.php
DOCKERFILE_APPEND

docker build \
  --build-arg ELABFTW_VERSION="$ELABFTW_VERSION" \
  -t "$ELAB_WEB_IMAGE" \
  "$WORK_DIR"

echo "Built image: $ELAB_WEB_IMAGE"
