#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEFAULT_FLEET_MANAGER_HOST="$(bash "${ROOT_DIR}/scripts/rpi/default_fleet_manager_host.sh")"
DEFAULT_FLEET_MANAGER_PORT="$(bash "${ROOT_DIR}/scripts/rpi/default_fleet_manager_port.sh")"

PI_HOST="${PI_HOST:-${1:-monad-rpi5.local}}"
PI_USER="${PI_USER:-admin}"
PI_DIR="${PI_DIR:-/home/${PI_USER}/monad-fleet-agent}"
SSH_IDENTITY_FILE="${SSH_IDENTITY_FILE:-}"
SSH_PROXY_JUMP="${SSH_PROXY_JUMP:-}"
SSH_USER_KNOWN_HOSTS_FILE="${SSH_USER_KNOWN_HOSTS_FILE:-}"
SSH_STRICT_HOST_KEY_CHECKING="${SSH_STRICT_HOST_KEY_CHECKING:-accept-new}"
USE_DEFAULT_SSH_KEY="${USE_DEFAULT_SSH_KEY:-false}"
DEFAULT_SSH_KEY="${ROOT_DIR}/scripts/rpi/keys/monad_rpi5_ed25519"
if [[ -z "${SSH_IDENTITY_FILE}" && "${USE_DEFAULT_SSH_KEY}" == "true" && -f "${DEFAULT_SSH_KEY}" ]]; then
  SSH_IDENTITY_FILE="${DEFAULT_SSH_KEY}"
fi

SSH_ARGS=()
if [[ -n "${SSH_STRICT_HOST_KEY_CHECKING}" ]]; then
  SSH_ARGS+=(-o "StrictHostKeyChecking=${SSH_STRICT_HOST_KEY_CHECKING}")
fi
if [[ -n "${SSH_USER_KNOWN_HOSTS_FILE}" ]]; then
  SSH_ARGS+=(-o "UserKnownHostsFile=${SSH_USER_KNOWN_HOSTS_FILE}")
fi
if [[ -n "${SSH_IDENTITY_FILE}" ]]; then
  SSH_ARGS+=(-i "${SSH_IDENTITY_FILE}" -o IdentitiesOnly=yes)
fi
if [[ -n "${SSH_PROXY_JUMP}" ]]; then
  SSH_ARGS+=(-J "${SSH_PROXY_JUMP}")
fi

run_ssh() {
  if [[ ${#SSH_ARGS[@]} -gt 0 ]]; then
    ssh "${SSH_ARGS[@]}" "$@"
  else
    ssh "$@"
  fi
}

FLEET_MANAGER_HOST="${FLEET_MANAGER_HOST:-${DEFAULT_FLEET_MANAGER_HOST}}"
CURRENT_REMOTE_FLEET_MANAGER_PORT="$(run_ssh "${PI_USER}@${PI_HOST}" "sed -n 's/^FLEET_MANAGER_PORT=//p' '${PI_DIR}/.env' 2>/dev/null | head -n1" 2>/dev/null || true)"
FLEET_MANAGER_PORT="${FLEET_MANAGER_PORT:-${CURRENT_REMOTE_FLEET_MANAGER_PORT:-${DEFAULT_FLEET_MANAGER_PORT}}}"
GRPC_DNS_RESOLVER="${GRPC_DNS_RESOLVER:-native}"
CONTROL_PLANE_MODE="${CONTROL_PLANE_MODE:-RF_SHARING}"
CONTROL_PLANE_IFACE="${CONTROL_PLANE_IFACE:-wlan0}"
WIFI_SCAN_IFACE="${WIFI_SCAN_IFACE:-${CONTROL_PLANE_IFACE}}"
MAX_SYNC_CYCLES="${MAX_SYNC_CYCLES:-0}"
EXECUTE_POLICY="${EXECUTE_POLICY:-true}"
CAPABILITIES="${CAPABILITIES:-csi,ble,wifi}"
DATA_ROOT="${DATA_ROOT:-${PI_DIR}/data}"
SENT_RETENTION_DAYS="${SENT_RETENTION_DAYS:-14}"
ARTIFACT_UPLOAD_TARGET="${ARTIFACT_UPLOAD_TARGET:-elabftw}"
ARTIFACT_UPLOAD_DURING_MEASURE="${ARTIFACT_UPLOAD_DURING_MEASURE:-true}"
ARTIFACT_EVICT_AFTER_UPLOAD="${ARTIFACT_EVICT_AFTER_UPLOAD:-true}"
ARTIFACT_UPLOAD_DURING_MEASURE_TIMEOUT_S="${ARTIFACT_UPLOAD_DURING_MEASURE_TIMEOUT_S:-3}"
ARTIFACT_UPLOAD_BACKOFF_S="${ARTIFACT_UPLOAD_BACKOFF_S:-15}"
GRPC_ARTIFACT_CHUNK_BYTES="${GRPC_ARTIFACT_CHUNK_BYTES:-1024}"
ENABLE_COMMAND_STATUS_REPORTS="${ENABLE_COMMAND_STATUS_REPORTS:-true}"
ENABLE_UPLOAD_STATUS_REPORTS="${ENABLE_UPLOAD_STATUS_REPORTS:-true}"
RUN_ARTIFACT_SOFT_LIMIT_BYTES="${RUN_ARTIFACT_SOFT_LIMIT_BYTES:-0}"
UPLOAD_WINDOW_FROM="${UPLOAD_WINDOW_FROM:-}"
UPLOAD_WINDOW_TO="${UPLOAD_WINDOW_TO:-}"
UPLOAD_WINDOW_REQUIRED="${UPLOAD_WINDOW_REQUIRED:-false}"
UPLOAD_SLOT_COUNT="${UPLOAD_SLOT_COUNT:-1}"
UPLOAD_SLOT_JITTER_S="${UPLOAD_SLOT_JITTER_S:-0}"
PROM_REMOTE_WRITE_ON_CMD="${PROM_REMOTE_WRITE_ON_CMD:-}"
PROM_REMOTE_WRITE_OFF_CMD="${PROM_REMOTE_WRITE_OFF_CMD:-}"
PROM_REMOTE_WRITE_CMD_TIMEOUT_S="${PROM_REMOTE_WRITE_CMD_TIMEOUT_S:-12}"
CSI_COLLECTOR_VERBOSE="${CSI_COLLECTOR_VERBOSE:-false}"
CSI_VERBOSE_FLAG=""
if [[ "${CSI_COLLECTOR_VERBOSE}" == "true" ]]; then
  CSI_VERBOSE_FLAG=" -v"
fi
CSI_COLLECTOR_CMD="${CSI_COLLECTOR_CMD:-sudo feitcsi --frequency 5240 --channel-width 80 --format VHT --output-file /tmp/csi.dat${CSI_VERBOSE_FLAG}}"
CSI_OUTPUT_PATH="${CSI_OUTPUT_PATH:-/tmp/csi.dat}"
CSI_REQUIRE_EVIDENCE="${CSI_REQUIRE_EVIDENCE:-true}"
CSI_MIN_FRAMES="${CSI_MIN_FRAMES:-1}"
CSI_MIN_OUTPUT_FILES="${CSI_MIN_OUTPUT_FILES:-1}"
CSI_SUDO_NONINTERACTIVE="${CSI_SUDO_NONINTERACTIVE:-true}"
SINGLE_RADIO_MODE="${SINGLE_RADIO_MODE:-false}"
SINGLE_RADIO_WIFI_PROFILE="${SINGLE_RADIO_WIFI_PROFILE:-auto}"
SINGLE_RADIO_RECOVERY_RETRIES="${SINGLE_RADIO_RECOVERY_RETRIES:-3}"
SINGLE_RADIO_RECOVERY_ROUTE_WAIT_S="${SINGLE_RADIO_RECOVERY_ROUTE_WAIT_S:-45}"
SINGLE_RADIO_RECOVERY_CMD="${SINGLE_RADIO_RECOVERY_CMD:-}"
SINGLE_RADIO_ROUTE_GATE="${SINGLE_RADIO_ROUTE_GATE:-true}"
SINGLE_RADIO_ROUTE_HEALTH_TIMEOUT_S="${SINGLE_RADIO_ROUTE_HEALTH_TIMEOUT_S:-5}"
SINGLE_RADIO_REBOOT_ON_RECOVERY_FAIL="${SINGLE_RADIO_REBOOT_ON_RECOVERY_FAIL:-false}"
CSI_HARD_TIMEOUT_S="${CSI_HARD_TIMEOUT_S:-20}"
CSI_CLEANUP_BEFORE_CAPTURE="${CSI_CLEANUP_BEFORE_CAPTURE:-true}"
CSI_CLEANUP_AFTER_CAPTURE="${CSI_CLEANUP_AFTER_CAPTURE:-true}"
CSI_KILL_PATTERNS="${CSI_KILL_PATTERNS:-feitcsi}"
AGENT_ID="${AGENT_ID:-}"

if [[ -z "${AGENT_ID}" ]]; then
  AGENT_ID="$(run_ssh "${PI_USER}@${PI_HOST}" "cat /sys/class/net/${CONTROL_PLANE_IFACE}/address")"
fi

echo "Installing systemd unit on ${PI_USER}@${PI_HOST}"
echo "Using AGENT_ID=${AGENT_ID}"
echo "Using FLEET_MANAGER_HOST=${FLEET_MANAGER_HOST} (GRPC_DNS_RESOLVER=${GRPC_DNS_RESOLVER})"

run_ssh "${PI_USER}@${PI_HOST}" "bash -s" <<EOF
set -euo pipefail

PI_DIR="${PI_DIR}"
mkdir -p "\${PI_DIR}"

cat > "\${PI_DIR}/.env" <<ENV
FLEET_MANAGER_HOST=${FLEET_MANAGER_HOST}
FLEET_MANAGER_PORT=${FLEET_MANAGER_PORT}
GRPC_DNS_RESOLVER=${GRPC_DNS_RESOLVER}
AGENT_ID=${AGENT_ID}
CONTROL_PLANE_MODE=${CONTROL_PLANE_MODE}
CONTROL_PLANE_IFACE=${CONTROL_PLANE_IFACE}
WIFI_SCAN_IFACE=${WIFI_SCAN_IFACE}
MAX_SYNC_CYCLES=${MAX_SYNC_CYCLES}
EXECUTE_POLICY=${EXECUTE_POLICY}
CAPABILITIES=${CAPABILITIES}
DATA_ROOT=${DATA_ROOT}
SENT_RETENTION_DAYS=${SENT_RETENTION_DAYS}
ARTIFACT_UPLOAD_TARGET=${ARTIFACT_UPLOAD_TARGET}
ARTIFACT_UPLOAD_DURING_MEASURE=${ARTIFACT_UPLOAD_DURING_MEASURE}
ARTIFACT_EVICT_AFTER_UPLOAD=${ARTIFACT_EVICT_AFTER_UPLOAD}
ARTIFACT_UPLOAD_DURING_MEASURE_TIMEOUT_S=${ARTIFACT_UPLOAD_DURING_MEASURE_TIMEOUT_S}
ARTIFACT_UPLOAD_BACKOFF_S=${ARTIFACT_UPLOAD_BACKOFF_S}
GRPC_ARTIFACT_CHUNK_BYTES=${GRPC_ARTIFACT_CHUNK_BYTES}
ENABLE_COMMAND_STATUS_REPORTS=${ENABLE_COMMAND_STATUS_REPORTS}
ENABLE_UPLOAD_STATUS_REPORTS=${ENABLE_UPLOAD_STATUS_REPORTS}
RUN_ARTIFACT_SOFT_LIMIT_BYTES=${RUN_ARTIFACT_SOFT_LIMIT_BYTES}
UPLOAD_WINDOW_FROM=${UPLOAD_WINDOW_FROM}
UPLOAD_WINDOW_TO=${UPLOAD_WINDOW_TO}
UPLOAD_WINDOW_REQUIRED=${UPLOAD_WINDOW_REQUIRED}
UPLOAD_SLOT_COUNT=${UPLOAD_SLOT_COUNT}
UPLOAD_SLOT_JITTER_S=${UPLOAD_SLOT_JITTER_S}
PROM_REMOTE_WRITE_ON_CMD="${PROM_REMOTE_WRITE_ON_CMD}"
PROM_REMOTE_WRITE_OFF_CMD="${PROM_REMOTE_WRITE_OFF_CMD}"
PROM_REMOTE_WRITE_CMD_TIMEOUT_S=${PROM_REMOTE_WRITE_CMD_TIMEOUT_S}
CSI_COLLECTOR_CMD="${CSI_COLLECTOR_CMD}"
CSI_OUTPUT_PATH=${CSI_OUTPUT_PATH}
CSI_REQUIRE_EVIDENCE=${CSI_REQUIRE_EVIDENCE}
CSI_MIN_FRAMES=${CSI_MIN_FRAMES}
CSI_MIN_OUTPUT_FILES=${CSI_MIN_OUTPUT_FILES}
CSI_SUDO_NONINTERACTIVE=${CSI_SUDO_NONINTERACTIVE}
SINGLE_RADIO_MODE=${SINGLE_RADIO_MODE}
SINGLE_RADIO_WIFI_PROFILE=${SINGLE_RADIO_WIFI_PROFILE}
SINGLE_RADIO_RECOVERY_RETRIES=${SINGLE_RADIO_RECOVERY_RETRIES}
SINGLE_RADIO_RECOVERY_ROUTE_WAIT_S=${SINGLE_RADIO_RECOVERY_ROUTE_WAIT_S}
SINGLE_RADIO_RECOVERY_CMD="${SINGLE_RADIO_RECOVERY_CMD}"
SINGLE_RADIO_ROUTE_GATE=${SINGLE_RADIO_ROUTE_GATE}
SINGLE_RADIO_ROUTE_HEALTH_TIMEOUT_S=${SINGLE_RADIO_ROUTE_HEALTH_TIMEOUT_S}
SINGLE_RADIO_REBOOT_ON_RECOVERY_FAIL=${SINGLE_RADIO_REBOOT_ON_RECOVERY_FAIL}
CSI_HARD_TIMEOUT_S=${CSI_HARD_TIMEOUT_S}
CSI_CLEANUP_BEFORE_CAPTURE=${CSI_CLEANUP_BEFORE_CAPTURE}
CSI_CLEANUP_AFTER_CAPTURE=${CSI_CLEANUP_AFTER_CAPTURE}
CSI_KILL_PATTERNS=${CSI_KILL_PATTERNS}
ENV

sudo tee /etc/systemd/system/monad-fleet-agent.service >/dev/null <<UNIT
[Unit]
Description=Monad Fleet Agent v2
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${PI_USER}
WorkingDirectory=${PI_DIR}
EnvironmentFile=${PI_DIR}/.env
ExecStart=${PI_DIR}/venv/bin/python -u ${PI_DIR}/agent_v2_client.py
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
UNIT

sudo systemctl daemon-reload
sudo systemctl enable --now monad-fleet-agent.service
sudo systemctl restart monad-fleet-agent.service
sudo systemctl is-enabled monad-fleet-agent.service
sudo systemctl is-active monad-fleet-agent.service
EOF

echo "systemd service installed and restarted."
