# elabftw nginx configuration file
# https://github.com/elabftw/elabimg
# values between "%" are replaced by prepare.sh script at container launch
daemon off;
pid /run/nginx.pid;
user nginx nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    server_tokens off;
    default_type application/octet-stream;
    sendfile on;
    underscores_in_headers on;
    client_body_timeout 3600s;
    client_header_timeout 10s;
    send_timeout 3600s;
    keepalive_timeout 10s;
    client_max_body_size 2G;
    include conf.d/*.conf;
}
