# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fleet_gateway_v3_pb2 as fleet__gateway__v3__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fleet_gateway_v3_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/fleet.v3.FleetManager/Hello',
                request_serializer=fleet__gateway__v3__pb2.HelloRequest.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/fleet.v3.FleetManager/GetPolicy',
                request_serializer=fleet__gateway__v3__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.GetPolicyResponse.FromString,
                _registered_method=True)
        self.AckPrepared = channel.unary_unary(
                '/fleet.v3.FleetManager/AckPrepared',
                request_serializer=fleet__gateway__v3__pb2.AckPreparedRequest.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.AckPreparedResponse.FromString,
                _registered_method=True)
        self.ReportCommandStatus = channel.unary_unary(
                '/fleet.v3.FleetManager/ReportCommandStatus',
                request_serializer=fleet__gateway__v3__pb2.ReportCommandStatusRequest.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.StatusAck.FromString,
                _registered_method=True)
        self.ReportUploadStatus = channel.unary_unary(
                '/fleet.v3.FleetManager/ReportUploadStatus',
                request_serializer=fleet__gateway__v3__pb2.ReportUploadStatusRequest.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.StatusAck.FromString,
                _registered_method=True)
        self.ReportArtifactUploadStatus = channel.unary_unary(
                '/fleet.v3.FleetManager/ReportArtifactUploadStatus',
                request_serializer=fleet__gateway__v3__pb2.ReportArtifactUploadStatusRequest.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.StatusAck.FromString,
                _registered_method=True)
        self.UploadArtifact = channel.stream_unary(
                '/fleet.v3.FleetManager/UploadArtifact',
                request_serializer=fleet__gateway__v3__pb2.UploadArtifactChunk.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.UploadArtifactResponse.FromString,
                _registered_method=True)
        self.PublishReport = channel.unary_unary(
                '/fleet.v3.FleetManager/PublishReport',
                request_serializer=fleet__gateway__v3__pb2.PublishReportRequest.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.PublishReportResponse.FromString,
                _registered_method=True)
        self.PublishEvents = channel.unary_unary(
                '/fleet.v3.FleetManager/PublishEvents',
                request_serializer=fleet__gateway__v3__pb2.PublishEventsRequest.SerializeToString,
                response_deserializer=fleet__gateway__v3__pb2.PublishEventsResponse.FromString,
                _registered_method=True)


class FleetManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Hello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """PREPARE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckPrepared(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCommandStatus(self, request, context):
        """EXECUTION runtime status (command lifecycle)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportUploadStatus(self, request, context):
        """MAINTENANCE runtime status (metrics sink upload)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportArtifactUploadStatus(self, request, context):
        """MAINTENANCE runtime status (per-artifact upload)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadArtifact(self, request_iterator, context):
        """MAINTENANCE artifact body upload. The first stream message must be the header.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishReport(self, request, context):
        """REPORT
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvents(self, request, context):
        """OPTIONAL (DUAL_NIC only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=fleet__gateway__v3__pb2.HelloRequest.FromString,
                    response_serializer=fleet__gateway__v3__pb2.HelloResponse.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=fleet__gateway__v3__pb2.GetPolicyRequest.FromString,
                    response_serializer=fleet__gateway__v3__pb2.GetPolicyResponse.SerializeToString,
            ),
            'AckPrepared': grpc.unary_unary_rpc_method_handler(
                    servicer.AckPrepared,
                    request_deserializer=fleet__gateway__v3__pb2.AckPreparedRequest.FromString,
                    response_serializer=fleet__gateway__v3__pb2.AckPreparedResponse.SerializeToString,
            ),
            'ReportCommandStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCommandStatus,
                    request_deserializer=fleet__gateway__v3__pb2.ReportCommandStatusRequest.FromString,
                    response_serializer=fleet__gateway__v3__pb2.StatusAck.SerializeToString,
            ),
            'ReportUploadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportUploadStatus,
                    request_deserializer=fleet__gateway__v3__pb2.ReportUploadStatusRequest.FromString,
                    response_serializer=fleet__gateway__v3__pb2.StatusAck.SerializeToString,
            ),
            'ReportArtifactUploadStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportArtifactUploadStatus,
                    request_deserializer=fleet__gateway__v3__pb2.ReportArtifactUploadStatusRequest.FromString,
                    response_serializer=fleet__gateway__v3__pb2.StatusAck.SerializeToString,
            ),
            'UploadArtifact': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadArtifact,
                    request_deserializer=fleet__gateway__v3__pb2.UploadArtifactChunk.FromString,
                    response_serializer=fleet__gateway__v3__pb2.UploadArtifactResponse.SerializeToString,
            ),
            'PublishReport': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishReport,
                    request_deserializer=fleet__gateway__v3__pb2.PublishReportRequest.FromString,
                    response_serializer=fleet__gateway__v3__pb2.PublishReportResponse.SerializeToString,
            ),
            'PublishEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvents,
                    request_deserializer=fleet__gateway__v3__pb2.PublishEventsRequest.FromString,
                    response_serializer=fleet__gateway__v3__pb2.PublishEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fleet.v3.FleetManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fleet.v3.FleetManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.v3.FleetManager/Hello',
            fleet__gateway__v3__pb2.HelloRequest.SerializeToString,
            fleet__gateway__v3__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.v3.FleetManager/GetPolicy',
            fleet__gateway__v3__pb2.GetPolicyRequest.SerializeToString,
            fleet__gateway__v3__pb2.GetPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AckPrepared(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.v3.FleetManager/AckPrepared',
            fleet__gateway__v3__pb2.AckPreparedRequest.SerializeToString,
            fleet__gateway__v3__pb2.AckPreparedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCommandStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.v3.FleetManager/ReportCommandStatus',
            fleet__gateway__v3__pb2.ReportCommandStatusRequest.SerializeToString,
            fleet__gateway__v3__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportUploadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.v3.FleetManager/ReportUploadStatus',
            fleet__gateway__v3__pb2.ReportUploadStatusRequest.SerializeToString,
            fleet__gateway__v3__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportArtifactUploadStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.v3.FleetManager/ReportArtifactUploadStatus',
            fleet__gateway__v3__pb2.ReportArtifactUploadStatusRequest.SerializeToString,
            fleet__gateway__v3__pb2.StatusAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadArtifact(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fleet.v3.FleetManager/UploadArtifact',
            fleet__gateway__v3__pb2.UploadArtifactChunk.SerializeToString,
            fleet__gateway__v3__pb2.UploadArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.v3.FleetManager/PublishReport',
            fleet__gateway__v3__pb2.PublishReportRequest.SerializeToString,
            fleet__gateway__v3__pb2.PublishReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fleet.v3.FleetManager/PublishEvents',
            fleet__gateway__v3__pb2.PublishEventsRequest.SerializeToString,
            fleet__gateway__v3__pb2.PublishEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
